export const PROJECTS =
    [
        {
            id: 0,
            name: 'TweetBot',
            image: 'assets/images/twitterBot.png',
            image2: 'assets/logos/nodeLogo.png',
            image3: 'assets/logos/reactLogo.png',
            featured: true,
            link:'https://twitter.com/1funnybot',
            word:'twitter',
            description: 'Node RESTful CRUD GET operations Axios blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah ',
        },
        {
            id: 1,
            name: 'Java Chess',
            image: 'assets/images/javaChess.png',
            image2: 'assets/logos/javaLogo.png',
            category: 'Core Java',
            featured: true,
            link:'',
            word: 'Java', 
            description: 'Core Java and OOP principles demonstrating Encapsulation, Inheritance, Polymorphism and Multithreading over a client/server architecture.',
        },
        {
            id: 2,
            name: 'Ristorante',
            image: 'assets/logos/reactLogo.png',
            image2: 'assets/logos/nodeLogo.png',
            image3: 'assets/logos/reactLogo.png',
            image4: 'assets/logos/expressLogo.png',
            image5: 'assets/logos/MongoLogo.png',
            category: 'React Express Node MongoDB',
            featured: false, 
            link: '',
            description: 'A quintessential ConFusion experience, is it a vada or is it a donut?',
        },
        {
            id: 3,
            name: 'React Hooks Blog',
            image: 'assets/images/reactHooks.png',
            category: 'React Hooks ',
            featured: false,
            word:'github',
            link: 'http://www.google.com', 
            description: 'A delectable, semi-sweet New York Style Cheese Cake, with Graham cracker crust and spiced with Indian cardamoms',
        }
    ];