export const PROJECTS_LOADING = 'PROJECTS_LOADING'; 
export const PROJECTS_FAILED = 'PROJECTS_FAILED'; 
export const ADD_PROJECTS = 'ADD_PROJECTS'; 
export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITES = 'ADD_FAVORITES';