export const PROJECTS_LOADING = 'PROJECTS_LOADING'; 
export const PROJECTS_FAILED = 'PROJECTS_FAILED'; 
export const ADD_PROJECTS = 'ADD_PROJECTS'; 
<<<<<<< HEAD
=======
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
>>>>>>> 01d56c581dbdc40b3cfc78e09483f68fd497ee79
export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITES = 'ADD_FAVORITES';